version: '3.8'

networks:
  network-mongo:
    driver: bridge
    name: network-mongo

volumes:
  volume-mongo:
    name: volume-mongo

services:

  mongo:
    container_name: mongo
    image: mongo:jammy
    networks:
      - network-mongo
    #ports:
    #  - 27017:27017
    restart: always
    volumes:
      - volume-mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.0-alpha.4
    networks:
      - network-mongo
    ports:
      - 8080:8081
    restart: always
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_AUTH_DATABASE: db
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://admin:example@mongo:27017/
